# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e05051a4470fd9b4b7f2f603fbe6bee97d9a63fbae15cc5fa56e4a01f10410309c2a17e13bb4d79d3192e1cf13160f62f4092f7fff2aaec741a81794881d3c9a

test:
  secret_key_base: a8b3a1bbd835bce86c9611a0cd7c377272c385983a0f67c101f1e8277b82e152ec0dd927d15f9ce61a727c5ce8d6a25be2073638f3d0ed952378098bb48f5dee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
